class Branch {
  String attached;
  int branchCode;
  String branchName;
  String province;
  String branchLanIp;
  String primaryWan;
  String primaryCct;
  String primaryBw;
  String primaryService;
  String secondaryWan;
  String secondaryCct;
  String secondaryBw;
  String secondaryService;

  Branch({
    required this.attached,
    required this.branchCode,
    required this.branchName,
    required this.province,
    required this.branchLanIp,
    required this.primaryWan,
    required this.primaryCct,
    required this.primaryBw,
    required this.primaryService,
    required this.secondaryWan,
    required this.secondaryCct,
    required this.secondaryBw,
    required this.secondaryService,
  });
}
final List<Map<String, dynamic>> dummyBranchesData = [
  {
    'attached': 'no',
    'branch_code': 'MB001',
    'branch_name': 'Main Branch',
    'province': 'Western',
    'branch_lan_ip': '192.168.1.1',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-100',
    'primary_bw': '100Mbps',
    'primary_service': 'Fiber',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '50Mbps',
    'secondary_service': 'DSL',
  },
      {
        'attached': 'Device',
        'branch_code': '448',
        'branch_name': 'Addalachchenai (Routed)',
        'province': 'EP',
        'branch_lan_ip': '172.31.78.254',
        'primary_wan': '172.31.95.58',
        'primary_cct': 'D69443',
        'primary_bw': '2 Mbps',
        'primary_service': 'One Access Eth - Bridge',
        'secondary_wan': '10.3.3.42 (TBI)',
        'secondary_cct': 'LN-193',
        'secondary_bw': '-',
        'secondary_service': 'Lanka Com',
    },
    {
        'attached': 'Device',
        'branch_code': '487',
        'branch_name': 'Adikarigama-SLT Routed',
        'province': 'CP',
        'branch_lan_ip': '172.19.31.254',
        'primary_wan': '172.25.30.122',
        'primary_cct': 'D57489',
        'primary_bw': '2 Mbps',
        'primary_service': 'One Access Eth - Bridge',
        'secondary_wan': '(Inactive) 10.161.250.29 / 10.3.3.142',
        'secondary_cct': '765107123',
        'secondary_bw': '7.2M / 2M',
        'secondary_service': 'DBN 3G / LCN CCD-194',
    },
    {
        'attached': 'Device',
        'branch_code': '671',
        'branch_name': 'Administrative Complex Isurupaya',
        'province': 'WPS',
        'branch_lan_ip': '172.31.183.254',
        'primary_wan': '172.31.191.94',
        'primary_cct': 'D63615',
        'primary_bw': '2 Mbps',
        'primary_service': 'One Access V35 - Bridge',
        'secondary_wan': '10.0.0.238',
        'secondary_cct': '994632502',
        'secondary_bw': '2M',
        'secondary_service': 'DBN IP VPN',
    },
    {
        'attached': 'Device',
        'branch_code': '657',
        'branch_name': 'Agalawatta',
        'province': 'WPS',
        'branch_lan_ip': '172.16.146.254',
        'primary_wan': '172.25.96.2',
        'primary_cct': 'D66399',
        'primary_bw': '2 Mbps',
        'primary_service': 'One Access V35 - Bridge',
        'secondary_wan': '10.0.0.242',
        'secondary_cct': '994632212',
        'secondary_bw': '2M',
        'secondary_service': 'DBN IP VPN',
    },
    {
        'attached': 'Device',
        'branch_code': '488',
        'branch_name': 'Agarapathana',
        'province': 'CP',
        'branch_lan_ip': '172.31.33.254',
        'primary_wan': '172.25.95.90',
        'primary_cct': 'D68689',
        'primary_bw': '2 Mbps',
        'primary_service': '-',
        'secondary_wan': '10.3.2.18',
        'secondary_cct': 'LN-195',
        'secondary_bw': '2M',
        'secondary_service': 'LCN',
    },
    {
        'attached': 'Device',
        'branch_code': '276',
        'branch_name': 'Ahangama',
        'province': 'SP',
        'branch_lan_ip': '172.17.140.254',
        'primary_wan': '172.25.54.222',
        'primary_cct': 'D60185',
        'primary_bw': '2 Mbps',
        'primary_service': 'One Access V35 - Bridge',
        'secondary_wan': '10.0.0.246',
        'secondary_cct': '994632213',
        'secondary_bw': '2M',
        'secondary_service': 'DBN IP VPN',
    },
    {
        'attached': 'Device',
        'branch_code': '754',
        'branch_name': 'Ahungalla',
        'province': 'SP',
        'branch_lan_ip': '172.17.82.254',
        'primary_wan': '172.25.54.14',
        'primary_cct': 'D57540',
        'primary_bw': '2 Mbps',
        'primary_service': 'One Access V35 - Bridge',
        'secondary_wan': '10.0.0.250',
        'secondary_cct': '994632214',
        'secondary_bw': '2M',
        'secondary_service': 'DBN IP VPN',
    },
    {
        'attached': 'Device',
        'branch_code': '590',
        'branch_name': 'Akkaraipattu',
        'province': 'EP',
        'branch_lan_ip': '172.16.150.254',
        'primary_wan': '172.25.96.6',
        'primary_cct': 'D68703',
        'primary_bw': '2 Mbps',
        'primary_service': '-',
        'secondary_wan': '10.3.0.10',
        'secondary_cct': '315-LN-36',
        'secondary_bw': '2M',
        'secondary_service': 'Lanka Com',
    },
    {
        'attached': 'Device',
        'branch_code': '489',
        'branch_name': 'Akurana',
        'province': 'Central',
        'branch_lan_ip': '172.31.20.254',
        'primary_wan': '172.25.95.50',
        'primary_cct': 'D69111',
        'primary_bw': '2 Mbps',
        'primary_service': '',
        'secondary_wan': '10.3.3.134',
        'secondary_cct': 'LN-196',
        'secondary_bw': '2 Mbps',
        'secondary_service': 'LCN',
    },
    {
        'attached': 'Device',
        'branch_code': '613',
        'branch_name': 'Akuressa',
        'province': 'Southern',
        'branch_lan_ip': '172.16.141.254',
        'primary_wan': '172.25.96.10',
        'primary_cct': 'D61073',
        'primary_bw': '2 Mbps',
        'primary_service': 'IP VPN',
        'secondary_wan': '10.0.0.254',
        'secondary_cct': '994632215',
        'secondary_bw': '2 Mbps',
        'secondary_service': 'DBN IP VPN',
    },
    {
        'attached': 'Device',
        'branch_code': '812',
        'branch_name': 'Aladeniya',
        'province': 'Central',
        'branch_lan_ip': '172.19.21.254',
        'primary_wan': '172.25.30.82',
        'primary_cct': 'D97739(New) /D45826',
        'primary_bw': '2 Mbps',
        'primary_service': '',
        'secondary_wan': '10.0.3.186',
        'secondary_cct': '994634367',
        'secondary_bw': '2 Mbps',
        'secondary_service': 'DBN IP VPN',
    },
    {
        'attached': 'Device',
        'branch_code': '449',
        'branch_name': 'Alankerny',
        'province': 'Eastern',
        'branch_lan_ip': '172.31.214.254',
        'primary_wan': '172.31.223.90',
        'primary_cct': 'D69792',
        'primary_bw': '2 Mbps',
        'primary_service': '',
        'secondary_wan': '10.3.2.146',
        'secondary_cct': '315-LN-228',
        'secondary_bw': '2 Mbps',
        'secondary_service': '-',
    },
    {
        'attached': 'Device',
        'branch_code': '380',
        'branch_name': 'Alaveddy',
        'province': 'Northern',
        'branch_lan_ip': '172.31.245.254',
        'primary_wan': '172.31.255.86',
        'primary_cct': 'D72801',
        'primary_bw': '2 Mbps',
        'primary_service': 'IP VPN',
        'secondary_wan': '10.0.1.2',
        'secondary_cct': '994632408',
        'secondary_bw': '2 Mbps',
        'secondary_service': 'DBN IP VPN',
    },
    {
        'attached': 'Device',
        'branch_code': '768',
        'branch_name': 'Alawathugoda',
        'province': 'Central',
        'branch_lan_ip': '172.16.220.254',
        'primary_wan': '172.25.29.110',
        'primary_cct': 'D69112',
        'primary_bw': '2 Mbps',
        'primary_service': 'IP VPN',
        'secondary_wan': '10.0.1.6',
        'secondary_cct': '994632521',
        'secondary_bw': '2 Mbps',
        'secondary_service': 'DBN IP VPN',
    },
    {
        'attached': 'Device',
        'branch_code': '498',
        'branch_name': 'Alawwa',
        'province': 'North Western',
        'branch_lan_ip': '172.16.215.254',
        'primary_wan': '172.25.29.54',
        'primary_cct': 'D61592',
        'primary_bw': '2 Mbps',
        'primary_service': '',
        'secondary_wan': '10.3.0.14',
        'secondary_cct': '315-LN-37',
        'secondary_bw': '2 Mbps',
        'secondary_service': 'Lanka Com',
    },
    {
        'attached': 'Device',
        'branch_code': '680',
        'branch_name': 'Aluthgama',
        'province': 'Western Province South',
        'branch_lan_ip': '172.16.10.254',
        'primary_wan': '172.25.94.10',
        'primary_cct': 'D51457',
        'primary_bw': '2 Mbps',
        'primary_service': 'IP VPN',
        'secondary_wan': '10.3.0.18',
        'secondary_cct': '315-LN-38',
        'secondary_bw': '2 Mbps',
        'secondary_service': 'Lanka Com',
    },
    {
        'attached': 'Device',
        'branch_code': '277',
        'branch_name': 'Aluthwala',
        'province': 'Southern',
        'branch_lan_ip': '172.31.140.254',
        'primary_wan': '172.31.159.50',
        'primary_cct': 'E1101111/D70821',
        'primary_bw': '2 Mbps',
        'primary_service': '',
        'secondary_wan': '10.3.2.78',
        'secondary_cct': 'LN-222',
        'secondary_bw': '2 Mbps',
        'secondary_service': 'LCN',
    },
    {
        'attached': 'Device',
        'branch_code': '47',
        'branch_name': 'Ambalangoda',
        'province': 'Southern',
        'branch_lan_ip': '172.16.69.254',
        'primary_wan': '172.25.94.14',
        'primary_cct': 'D63438',
        'primary_bw': '2 Mbps',
        'primary_service': 'One Access V35 - Bridge',
        'secondary_wan': '10.0.0.18',
        'secondary_cct': '997004592',
        'secondary_bw': '2 Mbps',
        'secondary_service': 'DBN IP VPN',
    },
 {
  "attached": "Device",
  "branch_code": "MB001",
  "branch_name": "Main Branch",
  "province": "Western",
  "branch_lan_ip": "192.168.1.1",
  "primary_wan": "WAN-1",
  "primary_cct": "CCT-120",
  "primary_bw": "100Mbps",
  "primary_service": "Fiber",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-200",
  "secondary_bw": "50Mbps",
  "secondary_service": "DSL"
},
{
  "attached": "Device",
  "branch_code": "MB002",
  "branch_name": "Ambalantota",
  "province": "Southern",
  "branch_lan_ip": "172.16.11.254",
  "primary_wan": "WAN-1",
  "primary_cct": "D66402",
  "primary_bw": "2Mbps",
  "primary_service": "One Access V35 - Bridge",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-120",
  "secondary_bw": "2Mbps",
  "secondary_service": "Lanka Com"
},
{
  "attached": "Device",
  "branch_code": "MB003",
  "branch_name": "Ambanpola",
  "province": "North Western",
  "branch_lan_ip": "172.17.133.254",
  "primary_wan": "WAN-1",
  "primary_cct": "D60177",
  "primary_bw": "2Mbps",
  "primary_service": "DBN IP VPN",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-200",
  "secondary_bw": "2Mbps",
  "secondary_service": "Lanka Com"
},
{
  "attached": "Device",
  "branch_code": "MB004",
  "branch_name": "Ampara",
  "province": "Eastern",
  "branch_lan_ip": "172.16.70.254",
  "primary_wan": "WAN-1",
  "primary_cct": "D51523",
  "primary_bw": "2Mbps",
  "primary_service": "IP VPN",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-120",
  "secondary_bw": "2Mbps",
  "secondary_service": "Lanka Com"
},
{
  "attached": "Device",
  "branch_code": "MB005",
  "branch_name": "Anamaduwa",
  "province": "North Western",
  "branch_lan_ip": "172.16.217.254",
  "primary_wan": "WAN-1",
  "primary_cct": "D61758",
  "primary_bw": "2Mbps",
  "primary_service": "IP VPN",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-200",
  "secondary_bw": "2Mbps",
  "secondary_service": "DBN IP VPN"
},
{
  "attached": "Device",
  "branch_code": "MB006",
  "branch_name": "Anavilundawa",
  "province": "North Western",
  "branch_lan_ip": "172.31.136.254",
  "primary_wan": "WAN-1",
  "primary_cct": "D69899",
  "primary_bw": "2Mbps",
  "primary_service": "Lanka Com",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-200",
  "secondary_bw": "2Mbps",
  "secondary_service": "Lanka Com"
},
{
  "attached": "Device",
  "branch_code": "MB007",
  "branch_name": "Adampan (Andankulam)",
  "province": "Northern",
  "branch_lan_ip": "172.31.89.254",
  "primary_wan": "WAN-1",
  "primary_cct": "D59045",
  "primary_bw": "2Mbps",
  "primary_service": "One Access Eth - Bridge",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-200",
  "secondary_bw": "2Mbps",
  "secondary_service": "Lanka Com"
},
{
  "attached": "Device",
  "branch_code": "MB008",
  "branch_name": "Andiambalama",
  "province": "Western",
  "branch_lan_ip": "172.16.242.254",
  "primary_wan": "WAN-1",
  "primary_cct": "D67431",
  "primary_bw": "2Mbps",
  "primary_service": "IP VPN",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-200",
  "secondary_bw": "2Mbps",
  "secondary_service": "DBN IP VPN"
},
{
  "attached": "Device",
  "branch_code": "MB009",
  "branch_name": "Angunakolapellasa",
  "province": "Southern",
  "branch_lan_ip": "172.17.141.254",
  "primary_wan": "WAN-1",
  "primary_cct": "D68795",
  "primary_bw": "2Mbps",
  "primary_service": "One Access V35 - Bridge",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-120",
  "secondary_bw": "2Mbps",
  "secondary_service": "Lanka Com"
},
{
  "attached": "Device",
  "branch_code": "MB010",
  "branch_name": "Ankumbura",
  "province": "Central",
  "branch_lan_ip": "172.31.153.254",
  "primary_wan": "WAN-1",
  "primary_cct": "D69113",
  "primary_bw": "2Mbps",
  "primary_service": "IP VPN",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-200",
  "secondary_bw": "2Mbps",
  "secondary_service": "DBN IP VPN"
},
{
    "attached": "Device",
    "branch_code": "MB001",
    "branch_name": "Anuradhapura City",
    "province": "North Central",
    "branch_lan_ip": "172.16.71.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-120",
    "primary_bw": "2Mbps",
    "primary_service": "Lanka Com",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "Fiber"
  },
  {
    "attached": "Device",
    "branch_code": "MB002",
    "branch_name": "Anuradhapura N'Town",
    "province": "North Central",
    "branch_lan_ip": "172.16.156.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-120",
    "primary_bw": "2Mbps",
    "primary_service": "Lanka Com",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "One Access Eth - Bridge"
  },
  {
    "attached": "Device",
    "branch_code": "MB003",
    "branch_name": "Aralaganwila",
    "province": "North Central",
    "branch_lan_ip": "172.17.76.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-120",
    "primary_bw": "2Mbps",
    "primary_service": "LCN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "Fiber"
  },
  {
    "attached": "Device",
    "branch_code": "MB004",
    "branch_name": "Aranayake",
    "province": "Sabaragamuwa",
    "branch_lan_ip": "172.17.40.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-120",
    "primary_bw": "2Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB005",
    "branch_name": "Ariyampathy",
    "province": "Eastern",
    "branch_lan_ip": "172.31.22.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-120",
    "primary_bw": "2Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "Fiber"
  },
  {
    "attached": "Device",
    "branch_code": "MB006",
    "branch_name": "Asiri Central Hospital",
    "province": "Western",
    "branch_lan_ip": "172.31.109.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-120",
    "primary_bw": "2Mbps",
    "primary_service": "Lanka Com",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "Fiber"
  },
  {
    "attached": "Device",
    "branch_code": "MB007",
    "branch_name": "Atchuvely",
    "province": "Northern",
    "branch_lan_ip": "172.17.235.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-120",
    "primary_bw": "2Mbps",
    "primary_service": "Lanka Com",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB008",
    "branch_name": "Athurugiriya",
    "province": "Western",
    "branch_lan_ip": "172.17.11.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-120",
    "primary_bw": "2Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB009",
    "branch_name": "Avissawella",
    "province": "Sabaragamuwa",
    "branch_lan_ip": "172.16.72.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-120",
    "primary_bw": "2Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB010",
    "branch_name": "Ayagama",
    "province": "Sabaragamuwa",
    "branch_lan_ip": "172.17.5.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-120",
    "primary_bw": "2Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "Fiber"
  },
{
    'attached': 'Device',
    'branch_code': 'MB001',
    'branch_name': 'Main Branch',
    'province': 'Western',
    'branch_lan_ip': '192.168.1.1',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '100Mbps',
    'primary_service': 'Fiber',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '50Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'BD001',
    'branch_name': 'Badalkumubura',
    'province': 'UVA',
    'branch_lan_ip': '172.17.109.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '2Mbps',
    'secondary_service': 'Lanka Com'
  },
  {
    'attached': 'Device',
    'branch_code': 'BD002',
    'branch_name': 'Baddegama',
    'province': 'SP',
    'branch_lan_ip': '172.17.84.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-110',
    'primary_bw': '2Mbps',
    'primary_service': 'Fiber',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-160',
    'secondary_bw': '2Mbps',
    'secondary_service': 'LankaCom'
  },
  {
    'attached': 'Device',
    'branch_code': 'BD003',
    'branch_name': 'Badulla',
    'province': 'UVA',
    'branch_lan_ip': '172.16.14.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-150',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-220',
    'secondary_bw': '2Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'BC001',
    'branch_name': 'Badulla City',
    'province': 'UVA',
    'branch_lan_ip': '172.17.209.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-100',
    'primary_bw': '2Mbps',
    'primary_service': 'LankaCom',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-190',
    'secondary_bw': '2Mbps',
    'secondary_service': 'Lanka Com'
  },
  {
    'attached': 'Device',
    'branch_code': 'BD004',
    'branch_name': 'Baduraliya',
    'province': 'WPS',
    'branch_lan_ip': '172.31.83.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-130',
    'primary_bw': '2Mbps',
    'primary_service': 'OA Eth Bridge',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-220',
    'secondary_bw': '2Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'BK001',
    'branch_name': 'Bakamoona',
    'province': 'NCP',
    'branch_lan_ip': '172.17.75.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-140',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-230',
    'secondary_bw': '2Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'BG001',
    'branch_name': 'Balangoda',
    'province': 'SAB',
    'branch_lan_ip': '172.16.73.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-150',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-210',
    'secondary_bw': '2Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'BK002',
    'branch_name': 'Balleketuwa',
    'province': 'UVA',
    'branch_lan_ip': '172.17.99.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-160',
    'primary_bw': '2Mbps',
    'primary_service': 'Fiber',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '2Mbps',
    'secondary_service': 'Lanka Com'
  },
  {
    'attached': 'Device',
    'branch_code': 'BG003',
    'branch_name': 'Bambalapitiya',
    'province': 'WPC',
    'branch_lan_ip': '172.16.5.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-110',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-190',
    'secondary_bw': '2Mbps',
    'secondary_service': 'DBN IP VPN'
  },
 {
    'attached': 'Device',
    'branch_code': 'MB001',
    'branch_name': 'Main Branch',
    'province': 'Western',
    'branch_lan_ip': '192.168.1.1',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '100Mbps',
    'primary_service': 'Fiber',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '50Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB002',
    'branch_name': 'Bandaragama',
    'province': 'WPS',
    'branch_lan_ip': '172.17.2.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '2 Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '2M',
    'secondary_service': 'Lanka Com'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB003',
    'branch_name': 'Bandarawela',
    'province': 'UVA',
    'branch_lan_ip': '172.16.75.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '2 Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '2M',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB004',
    'branch_name': 'Barawakumbuka',
    'province': 'SP',
    'branch_lan_ip': '172.31.41.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '2 Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '2M',
    'secondary_service': 'LCN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB005',
    'branch_name': 'Batapola',
    'province': 'SP',
    'branch_lan_ip': '172.17.44.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '2 Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '2M',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB006',
    'branch_name': 'Battaramulla',
    'province': 'WPS',
    'branch_lan_ip': '172.16.15.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '2 Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '2M',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB007',
    'branch_name': 'Batticaloa City Branch',
    'province': 'EP',
    'branch_lan_ip': '172.31.165.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '2 Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '2M',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB008',
    'branch_name': 'Batticaloa Super Grade',
    'province': 'EP',
    'branch_lan_ip': '172.16.16.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '2 Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '2M',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB009',
    'branch_name': 'Batuwatte',
    'province': 'WPN',
    'branch_lan_ip': '172.31.230.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '2 Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '2M',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB010',
    'branch_name': 'Beliatta',
    'province': 'SP',
    'branch_lan_ip': '172.16.243.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '2 Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '2M',
    'secondary_service': 'DBN IP VPN'
  },
{
    "attached": "Device",
    "branch_code": "MB001",
    "branch_name": "Main Branch",
    "province": "Western",
    "branch_lan_ip": "192.168.1.1",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-120",
    "primary_bw": "100Mbps",
    "primary_service": "Fiber",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "50Mbps",
    "secondary_service": "DSL"
  },
  {
    "attached": "Device",
    "branch_code": "BB002",
    "branch_name": "Bibile",
    "province": "UVA",
    "branch_lan_ip": "172.17.67.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D77026",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.3.0.54",
    "secondary_bw": "2M",
    "secondary_service": "Lanka Com"
  },
  {
    "attached": "Device",
    "branch_code": "BB003",
    "branch_name": "Bingiriya",
    "province": "NWP",
    "branch_lan_ip": "172.17.57.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D61496",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.0.1.62",
    "secondary_bw": "2M",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "BB004",
    "branch_name": "Biyagama",
    "province": "WPN",
    "branch_lan_ip": "172.16.77.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D66427",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.0.4.166",
    "secondary_bw": "2M",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "BB005",
    "branch_name": "Bogahakumbura",
    "province": "UVA",
    "branch_lan_ip": "172.17.198.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D70058",
    "primary_bw": "2Mbps",
    "primary_service": "None",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.0.1.66",
    "secondary_bw": "2M",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "BB006",
    "branch_name": "Bogaswewa",
    "province": "NCP",
    "branch_lan_ip": "172.19.25.254",
    "primary_wan": "WAN-1",
    "primary_cct": "E1106196/D54323",
    "primary_bw": "2Mbps",
    "primary_service": "One Access Eth - Bridge",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.0.5.130",
    "secondary_bw": "2M",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "BB007",
    "branch_name": "Bogawanthalawa",
    "province": "CP",
    "branch_lan_ip": "172.17.134.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D63635",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.0.1.70",
    "secondary_bw": "2M",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "BB008",
    "branch_name": "BOI Pallekele",
    "province": "CP",
    "branch_lan_ip": "172.31.249.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D69114",
    "primary_bw": "2Mbps",
    "primary_service": "None",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.0.4.82",
    "secondary_bw": "2M",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "BB009",
    "branch_name": "Bokkawala",
    "province": "CP",
    "branch_lan_ip": "172.17.197.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D47863",
    "primary_bw": "2Mbps",
    "primary_service": "None",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.0.1.74",
    "secondary_bw": "2M",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "BB010",
    "branch_name": "Bombuwela",
    "province": "WPS",
    "branch_lan_ip": "172.31.113.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D53040",
    "primary_bw": "2Mbps",
    "primary_service": "None",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.0.5.134",
    "secondary_bw": "2M",
    "secondary_service": "DBN IP VPN"
  },
{
  "attached": "Device",
  "branch_code": "MB001",
  "branch_name": "Main Branch",
  "province": "Western",
  "branch_lan_ip": "192.168.1.1",
  "primary_wan": "WAN-1",
  "primary_cct": "CCT-120",
  "primary_bw": "100Mbps",
  "primary_service": "Fiber",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-200",
  "secondary_bw": "50Mbps",
  "secondary_service": "DSL"
},
{
  "attached": "Device",
  "branch_code": "MB002",
  "branch_name": "Boragas",
  "province": "UVA",
  "branch_lan_ip": "172.31.243.254",
  "primary_wan": "WAN-1",
  "primary_cct": "CCT-120",
  "primary_bw": "2Mbps",
  "primary_service": "Lanka Com",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-200",
  "secondary_bw": "2Mbps",
  "secondary_service": "Lanka Com"
},
{
  "attached": "Device",
  "branch_code": "MB003",
  "branch_name": "Boralesgamuwa",
  "province": "WPS",
  "branch_lan_ip": "172.16.118.254",
  "primary_wan": "WAN-1",
  "primary_cct": "CCT-120",
  "primary_bw": "2Mbps",
  "primary_service": "IP VPN",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-200",
  "secondary_bw": "2Mbps",
  "secondary_service": "IP VPN"
},
{
  "attached": "Device",
  "branch_code": "MB004",
  "branch_name": "Borella",
  "province": "WPN",
  "branch_lan_ip": "172.16.138.254",
  "primary_wan": "WAN-1",
  "primary_cct": "CCT-120",
  "primary_bw": "2Mbps",
  "primary_service": "IP VPN",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-200",
  "secondary_bw": "2Mbps",
  "secondary_service": "IP VPN"
},
{
  "attached": "Device",
  "branch_code": "MB005",
  "branch_name": "Borella 2nd (SLT Routed)",
  "province": "WPN",
  "branch_lan_ip": "172.16.18.254",
  "primary_wan": "WAN-1",
  "primary_cct": "CCT-120",
  "primary_bw": "2Mbps",
  "primary_service": "Lanka Com",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-200",
  "secondary_bw": "2Mbps",
  "secondary_service": "Lanka Com"
},
{
  "attached": "Device",
  "branch_code": "MB006",
  "branch_name": "Bulathkohupitiya",
  "province": "SAB",
  "branch_lan_ip": "172.17.194.254",
  "primary_wan": "WAN-1",
  "primary_cct": "CCT-120",
  "primary_bw": "2Mbps",
  "primary_service": "IP VPN",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-200",
  "secondary_bw": "2Mbps",
  "secondary_service": "IP VPN"
},
{
  "attached": "Device",
  "branch_code": "MB007",
  "branch_name": "Bulathsinhala",
  "province": "WPS",
  "branch_lan_ip": "172.17.70.254",
  "primary_wan": "WAN-1",
  "primary_cct": "CCT-120",
  "primary_bw": "2Mbps",
  "primary_service": "IP VPN",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-200",
  "secondary_bw": "2Mbps",
  "secondary_service": "IP VPN"
},
{
  "attached": "Device",
  "branch_code": "MB008",
  "branch_name": "Buttala",
  "province": "UVA",
  "branch_lan_ip": "172.16.228.254",
  "primary_wan": "WAN-1",
  "primary_cct": "CCT-120",
  "primary_bw": "2Mbps",
  "primary_service": "Lanka Com",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-200",
  "secondary_bw": "2Mbps",
  "secondary_service": "Lanka Com"
},
{
  "attached": "Device",
  "branch_code": "MB009",
  "branch_name": "Central Bus Stand",
  "province": "WPN",
  "branch_lan_ip": "172.16.78.254",
  "primary_wan": "WAN-1",
  "primary_cct": "CCT-120",
  "primary_bw": "2Mbps",
  "primary_service": "IP VPN",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-200",
  "secondary_bw": "2Mbps",
  "secondary_service": "IP VPN"
},
{
  "attached": "Device",
  "branch_code": "MB010",
  "branch_name": "Ampara Central Camp",
  "province": "EP",
  "branch_lan_ip": "172.19.24.254",
  "primary_wan": "WAN-1",
  "primary_cct": "CCT-120",
  "primary_bw": "2Mbps",
  "primary_service": "Lanka Com",
  "secondary_wan": "WAN-2",
  "secondary_cct": "CCT-200",
  "secondary_bw": "2Mbps",
  "secondary_service": "Lanka Com"
},
{
    'attached': 'Device',
    'branch_code': 'MB001',
    'branch_name': 'Main Branch',
    'province': 'Western',
    'branch_lan_ip': '192.168.1.1',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '100Mbps',
    'primary_service': 'Fiber',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '50Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': '792',
    'branch_name': 'Chankanai',
    'province': 'NP',
    'branch_lan_ip': '172.17.233.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'D64981',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': '10.0.5.30',
    'secondary_bw': '2Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': '501',
    'branch_name': 'Chavakachcheri',
    'province': 'NP',
    'branch_lan_ip': '172.17.177.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'D58381',
    'primary_bw': '2Mbps',
    'primary_service': '',
    'secondary_wan': 'WAN-2',
    'secondary_cct': '10.3.2.130',
    'secondary_bw': '2Mbps',
    'secondary_service': 'LCN'
  },
  {
    'attached': 'Device',
    'branch_code': '382',
    'branch_name': 'Cheddikulam',
    'province': 'NP',
    'branch_lan_ip': '172.31.217.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'D69873',
    'primary_bw': '2Mbps',
    'primary_service': '',
    'secondary_wan': 'WAN-2',
    'secondary_cct': '10.0.1.94',
    'secondary_bw': '2Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': '630',
    'branch_name': 'Chenkaladi',
    'province': 'EP',
    'branch_lan_ip': '172.16.171.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'D68690',
    'primary_bw': '2Mbps',
    'primary_service': '',
    'secondary_wan': 'WAN-2',
    'secondary_cct': '10.3.0.66',
    'secondary_bw': '2Mbps',
    'secondary_service': 'Lanka Com'
  },
  {
    'attached': 'Device',
    'branch_code': '20',
    'branch_name': 'Chilaw',
    'province': 'NWP',
    'branch_lan_ip': '172.16.79.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'D51612',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': '10.0.0.54',
    'secondary_bw': '2Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': '436',
    'branch_name': 'China Bay',
    'province': 'EP',
    'branch_lan_ip': '172.31.76.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'D69469',
    'primary_bw': '2Mbps',
    'primary_service': '',
    'secondary_wan': 'WAN-2',
    'secondary_cct': '10.3.2.138',
    'secondary_bw': '2Mbps',
    'secondary_service': 'LCN'
  },
  {
    'attached': 'Device',
    'branch_code': '53',
    'branch_name': 'Chunnakam',
    'province': 'NP',
    'branch_lan_ip': '172.17.182.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'D61076',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': '10.3.0.70',
    'secondary_bw': '2Mbps',
    'secondary_service': 'Lanka Com'
  },
  {
    'attached': 'Device',
    'branch_code': '1',
    'branch_name': 'City Office',
    'province': 'WPN',
    'branch_lan_ip': '172.16.20.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'D79028',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': '10.0.0.58',
    'secondary_bw': '2Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': '474',
    'branch_name': 'Court Complex Kandy',
    'province': 'CP',
    'branch_lan_ip': '172.31.231.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'D69115',
    'primary_bw': '2Mbps',
    'primary_service': '',
    'secondary_wan': 'WAN-2',
    'secondary_cct': '10.3.2.158',
    'secondary_bw': '2Mbps',
    'secondary_service': 'LCN'
  },
  {
    "attached": "Device",
    "branch_code": "MB001",
    "branch_name": "Dambadeniya",
    "province": "NWP",
    "branch_lan_ip": "172.17.224.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D63964",
    "primary_bw": "2 Mbps",
    "primary_service": "LCN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.3.3.18",
    "secondary_bw": "2M",
    "secondary_service": "LN-238"
  },
  {
    "attached": "Device",
    "branch_code": "MB002",
    "branch_name": "Dambagalla (Routed)",
    "province": "UVA",
    "branch_lan_ip": "172.17.208.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D65021",
    "primary_bw": "2 Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.0.1.102",
    "secondary_bw": "2M",
    "secondary_service": "994632524"
  },
  {
    "attached": "Device",
    "branch_code": "MB003",
    "branch_name": "Dambulla",
    "province": "CP",
    "branch_lan_ip": "172.31.84.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D61068",
    "primary_bw": "2 Mbps",
    "primary_service": "IP VPN-CTUR BRI",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.0.1.106",
    "secondary_bw": "2M",
    "secondary_service": "994632225"
  },
  {
    "attached": "Device",
    "branch_code": "MB004",
    "branch_name": "Dankotuwa (Routed)",
    "province": "NWP",
    "branch_lan_ip": "172.16.22.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D66401",
    "primary_bw": "2 Mbps",
    "primary_service": "Lanka Com",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.3.0.74",
    "secondary_bw": "2M",
    "secondary_service": "315-LN-58"
  },
  {
    "attached": "Device",
    "branch_code": "MB005",
    "branch_name": "Danture",
    "province": "CP",
    "branch_lan_ip": "172.17.196.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D69116",
    "primary_bw": "2 Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.0.1.110",
    "secondary_bw": "2M",
    "secondary_service": "994632411"
  },
  {
    "attached": "Device",
    "branch_code": "MB006",
    "branch_name": "Daulagala",
    "province": "CP",
    "branch_lan_ip": "172.16.252.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D69915",
    "primary_bw": "2 Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.0.1.114",
    "secondary_bw": "2M",
    "secondary_service": "994632476"
  },
  {
    "attached": "Device",
    "branch_code": "MB007",
    "branch_name": "Dehiattakandiya",
    "province": "NCP",
    "branch_lan_ip": "172.16.248.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D61071",
    "primary_bw": "2 Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.0.4.18",
    "secondary_bw": "2M",
    "secondary_service": "994634241"
  },
  {
    "attached": "Device",
    "branch_code": "MB008",
    "branch_name": "Dehiowita",
    "province": "SAB",
    "branch_lan_ip": "172.16.163.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D65047",
    "primary_bw": "2 Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.0.1.118",
    "secondary_bw": "2M",
    "secondary_service": "994632486"
  },
  {
    "attached": "Device",
    "branch_code": "MB009",
    "branch_name": "Dehiwala",
    "province": "WPS",
    "branch_lan_ip": "172.16.81.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D51479",
    "primary_bw": "2 Mbps",
    "primary_service": "Lanka Com",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.3.0.82",
    "secondary_bw": "2M",
    "secondary_service": "315-LN-60"
  },
  {
    "attached": "Device",
    "branch_code": "MB010",
    "branch_name": "Deiyandara",
    "province": "SP",
    "branch_lan_ip": "172.17.142.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D77773",
    "primary_bw": "2 Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "10.0.1.122",
    "secondary_bw": "2M",
    "secondary_service": "994632487"
  },
  {
    'attached': 'Device',
    'branch_code': 'MB001',
    'branch_name': 'Main Branch',
    'province': 'Western',
    'branch_lan_ip': '192.168.1.1',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '100Mbps',
    'primary_service': 'Fiber',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '50Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB002',
    'branch_name': 'Delft',
    'province': 'Northern',
    'branch_lan_ip': '172.31.155.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '2Mbps',
    'primary_service': 'DBN-IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-150',
    'secondary_bw': '1Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB003',
    'branch_name': 'Delgoda',
    'province': 'Western',
    'branch_lan_ip': '172.31.96.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-150',
    'primary_bw': '2Mbps',
    'primary_service': 'DBN IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-160',
    'secondary_bw': '1Mbps',
    'secondary_service': 'One Access Eth - Bridge'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB004',
    'branch_name': 'Demanhandiya',
    'province': 'Western',
    'branch_lan_ip': '172.31.52.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-200',
    'primary_bw': '2Mbps',
    'primary_service': 'One Access',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-220',
    'secondary_bw': '1Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB005',
    'branch_name': 'Dematagoda',
    'province': 'Western',
    'branch_lan_ip': '172.16.196.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-210',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-230',
    'secondary_bw': '1Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB006',
    'branch_name': 'Deniyaya',
    'province': 'Southern',
    'branch_lan_ip': '172.16.197.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-220',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-240',
    'secondary_bw': '1Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB007',
    'branch_name': 'Deraniyagala',
    'province': 'Sabaragamuwa',
    'branch_lan_ip': '172.16.153.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-240',
    'primary_bw': '2Mbps',
    'primary_service': 'SLT Routed',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-250',
    'secondary_bw': '1Mbps',
    'secondary_service': 'IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB008',
    'branch_name': 'Devinuwara',
    'province': 'Southern',
    'branch_lan_ip': '172.16.249.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-250',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-260',
    'secondary_bw': '1Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB009',
    'branch_name': 'Dharga Town',
    'province': 'Western',
    'branch_lan_ip': '172.16.194.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-260',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-270',
    'secondary_bw': '1Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB010',
    'branch_name': 'Dickwella',
    'province': 'Southern',
    'branch_lan_ip': '172.16.162.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-270',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-280',
    'secondary_bw': '1Mbps',
    'secondary_service': 'Lanka Com'
  },
 {
    'attached': 'Device',
    'branch_code': 'DV001',
    'branch_name': 'Digana Village',
    'province': 'Central',
    'branch_lan_ip': '172.16.24.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '1Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'DP001',
    'branch_name': 'Divulupitiya',
    'province': 'Western',
    'branch_lan_ip': '172.16.195.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-110',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-201',
    'secondary_bw': '1Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'DY001',
    'branch_name': 'Diyabeduma',
    'province': 'Central',
    'branch_lan_ip': '172.31.211.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-202',
    'secondary_bw': '1Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'DY002',
    'branch_name': 'Diyasenpura',
    'province': 'Central',
    'branch_lan_ip': '172.31.210.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-130',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-203',
    'secondary_bw': '1Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'DY003',
    'branch_name': 'Diyatalawa',
    'province': 'Uva',
    'branch_lan_ip': '172.16.25.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-140',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-204',
    'secondary_bw': '1Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'DG001',
    'branch_name': 'Dodangoda',
    'province': 'Western',
    'branch_lan_ip': '172.16.98.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-150',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-205',
    'secondary_bw': '1Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'DM001',
    'branch_name': 'Doramadalawa',
    'province': 'Central',
    'branch_lan_ip': '172.31.49.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-160',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-206',
    'secondary_bw': '1Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'DS001',
    'branch_name': 'Dummalasuriya',
    'province': 'North Western',
    'branch_lan_ip': '172.17.78.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-170',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-207',
    'secondary_bw': '1Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'EU001',
    'branch_name': 'Eastern University',
    'province': 'Eastern',
    'branch_lan_ip': '172.31.114.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-180',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-208',
    'secondary_bw': '1Mbps',
    'secondary_service': 'DSL'
  },
 {
    'attached': 'Device',
    'branch_code': 'MB002',
    'branch_name': 'Elakanda',
    'province': 'Western',
    'branch_lan_ip': '172.31.252.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-258',
    'primary_bw': '2Mbps',
    'primary_service': 'One Access Eth - Bridge',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-120',
    'secondary_bw': '10Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB003',
    'branch_name': 'Ella',
    'province': 'Uva',
    'branch_lan_ip': '172.17.199.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-701',
    'primary_bw': '2Mbps',
    'primary_service': 'One Access V35 - Bridge',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-178',
    'secondary_bw': '5Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB004',
    'branch_name': 'Elpitiya',
    'province': 'Southern',
    'branch_lan_ip': '172.16.216.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-619',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-58',
    'secondary_bw': '10Mbps',
    'secondary_service': 'Lanka Com'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB005',
    'branch_name': 'Embilipitiya',
    'province': 'Sabaragamuwa',
    'branch_lan_ip': '172.16.123.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-535',
    'primary_bw': '2Mbps',
    'primary_service': 'One Access V35 - Bridge',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-110',
    'secondary_bw': '10Mbps',
    'secondary_service': 'Lanka Com'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB006',
    'branch_name': 'Embilipitiya City',
    'province': 'Sabaragamuwa',
    'branch_lan_ip': '172.17.226.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-312',
    'primary_bw': '2Mbps',
    'primary_service': 'One Access Eth - Bridge',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-96',
    'secondary_bw': '5Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB007',
    'branch_name': 'Endana',
    'province': 'Sabaragamuwa',
    'branch_lan_ip': '172.19.39.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-313',
    'primary_bw': '2Mbps',
    'primary_service': 'One Access V35 - Bridge',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-154',
    'secondary_bw': '10Mbps',
    'secondary_service': 'LCN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB008',
    'branch_name': 'Enderamulla',
    'province': 'Western',
    'branch_lan_ip': '172.31.115.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-674',
    'primary_bw': '2Mbps',
    'primary_service': 'One Access V35 - Bridge',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-218',
    'secondary_bw': '5Mbps',
    'secondary_service': 'LCN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB009',
    'branch_name': 'Eppawala',
    'province': 'North Central',
    'branch_lan_ip': '172.16.247.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-692',
    'primary_bw': '2Mbps',
    'primary_service': 'IP VPN',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-170',
    'secondary_bw': '5Mbps',
    'secondary_service': 'DBN IP VPN'
  },
  {
    'attached': 'Device',
    'branch_code': 'MB010',
    'branch_name': 'Eravur',
    'province': 'Eastern',
    'branch_lan_ip': '172.31.168.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-790',
    'primary_bw': '2Mbps',
    'primary_service': 'One Access Eth - Bridge',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-242',
    'secondary_bw': '5Mbps',
    'secondary_service': 'DBN IP VPN'
  },
{
    "attached": "Device",
    "branch_code": "MB001",
    "branch_name": "Ethimale",
    "province": "UVA",
    "branch_lan_ip": "172.19.26.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D46201",
    "primary_bw": "2 Mbps",
    "primary_service": "Lanka Com",
    "secondary_wan": "WAN-2",
    "secondary_cct": "LN - 247",
    "secondary_bw": "2M",
    "secondary_service": "LCN"
  },
  {
    "attached": "Device",
    "branch_code": "MB002",
    "branch_name": "Ettampitiya",
    "province": "UVA",
    "branch_lan_ip": "172.17.34.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D47762",
    "primary_bw": "2 Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "OA v35 Bridge",
    "secondary_bw": "2M",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB003",
    "branch_name": "Fifth City",
    "province": "WPN",
    "branch_lan_ip": "172.16.26.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D63541",
    "primary_bw": "2 Mbps",
    "primary_service": "Lanka Com",
    "secondary_wan": "WAN-2",
    "secondary_cct": "LN94",
    "secondary_bw": "2M",
    "secondary_service": "Lanka Com"
  },
  {
    "attached": "Device",
    "branch_code": "MB004",
    "branch_name": "Fish Market Peliyagoda",
    "province": "WPN",
    "branch_lan_ip": "172.31.138.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D67447",
    "primary_bw": "2 Mbps",
    "primary_service": "Lanka Com",
    "secondary_wan": "WAN-2",
    "secondary_cct": "LN94",
    "secondary_bw": "2M",
    "secondary_service": "Lanka Com"
  },
  {
    "attached": "Device",
    "branch_code": "MB005",
    "branch_name": "Galagedara",
    "province": "CP",
    "branch_lan_ip": "172.17.47.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D61529",
    "primary_bw": "2 Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "One Access",
    "secondary_bw": "2M",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB006",
    "branch_name": "Galaha",
    "province": "CP",
    "branch_lan_ip": "172.17.23.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D69119",
    "primary_bw": "2 Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "IP VPN",
    "secondary_bw": "2M",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB007",
    "branch_name": "Galamuna (Routed)",
    "province": "NCP",
    "branch_lan_ip": "172.17.187.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D47855",
    "primary_bw": "2 Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "DBN IP VPN",
    "secondary_bw": "2M",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB008",
    "branch_name": "Galenbindunuwewa",
    "province": "NCP",
    "branch_lan_ip": "172.17.55.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D78542",
    "primary_bw": "2 Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "IP VPN",
    "secondary_bw": "2M",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB009",
    "branch_name": "Galewela",
    "province": "CP",
    "branch_lan_ip": "172.16.205.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D51513",
    "primary_bw": "2 Mbps",
    "primary_service": "Lanka Com",
    "secondary_wan": "WAN-2",
    "secondary_cct": "LN-69",
    "secondary_bw": "2M",
    "secondary_service": "Lanka Com"
  },
  {
    "attached": "Device",
    "branch_code": "MB010",
    "branch_name": "Galgamuwa",
    "province": "NWP",
    "branch_lan_ip": "172.16.201.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D61793",
    "primary_bw": "2 Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "DBN IP VPN",
    "secondary_bw": "2M",
    "secondary_service": "DBN IP VPN"
  },
 {
    "attached": "Device",
    "branch_code": "MB002",
    "branch_name": "Galigamuwa (Routed to SLT with Backup line)",
    "province": "SAB",
    "branch_lan_ip": "172.17.192.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-314",
    "primary_bw": "2Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-120",
    "secondary_bw": "2Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB003",
    "branch_name": "Galkiriyagama",
    "province": "NCP",
    "branch_lan_ip": "172.17.90.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-653",
    "primary_bw": "2Mbps",
    "primary_service": "Lanka Com",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "50Mbps",
    "secondary_service": "DSL"
  },
  {
    "attached": "Device",
    "branch_code": "MB004",
    "branch_name": "Galle (SLT Routed)",
    "province": "SP",
    "branch_lan_ip": "172.16.85.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-51497",
    "primary_bw": "2Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-150",
    "secondary_bw": "2Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB005",
    "branch_name": "Galle City (Routed)",
    "province": "SP",
    "branch_lan_ip": "172.16.27.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-E1110759",
    "primary_bw": "2Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-142",
    "secondary_bw": "2Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB006",
    "branch_name": "Galnewa",
    "province": "NCP",
    "branch_lan_ip": "172.17.64.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-61795",
    "primary_bw": "2Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-198",
    "secondary_bw": "2Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB007",
    "branch_name": "Gampaha-Super Grade",
    "province": "WPN",
    "branch_lan_ip": "172.16.86.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-51597",
    "primary_bw": "2Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-150",
    "secondary_bw": "2Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB008",
    "branch_name": "Gampola",
    "province": "CP",
    "branch_lan_ip": "172.16.28.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-61442",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-154",
    "secondary_bw": "2Mbps",
    "secondary_service": "Lanka Com"
  },
  {
    "attached": "Device",
    "branch_code": "MB009",
    "branch_name": "Gampola City (Routed to SLT with Backup line)",
    "province": "CP",
    "branch_lan_ip": "172.17.207.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-69142",
    "primary_bw": "2Mbps",
    "primary_service": "LCN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-249",
    "secondary_bw": "2Mbps",
    "secondary_service": "LCN"
  },
  {
    "attached": "Device",
    "branch_code": "MB010",
    "branch_name": "Ganemulla",
    "province": "WPN",
    "branch_lan_ip": "172.17.188.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-67455",
    "primary_bw": "2Mbps",
    "primary_service": "DBN IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-146",
    "secondary_bw": "2Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB001",
    "branch_name": "General Hospital Anuradhapura",
    "province": "NCP",
    "branch_lan_ip": "172.31.160.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D52296",
    "primary_bw": "2 Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "DBN IP VPN",
    "secondary_bw": "2 Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB002",
    "branch_name": "Ginigathhena - Routed SLT",
    "province": "CP",
    "branch_lan_ip": "172.17.201.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D69143",
    "primary_bw": "2 Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "DBN IP VPN",
    "secondary_bw": "2 Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB003",
    "branch_name": "Girandurukotte (Routed)",
    "province": "UVA",
    "branch_lan_ip": "172.16.251.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D68821",
    "primary_bw": "2 Mbps",
    "primary_service": "One Access Eth - Bridge",
    "secondary_wan": "WAN-2",
    "secondary_cct": "Lanka Com",
    "secondary_bw": "2 Mbps",
    "secondary_service": "Lanka Com"
  },
  {
    "attached": "Device",
    "branch_code": "MB004",
    "branch_name": "Giriulla",
    "province": "NWP",
    "branch_lan_ip": "172.16.224.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D61706",
    "primary_bw": "2 Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "DBN IP VPN",
    "secondary_bw": "2 Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB005",
    "branch_name": "Godakawela",
    "province": "SAB",
    "branch_lan_ip": "172.31.80.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D63638",
    "primary_bw": "2 Mbps",
    "primary_service": "One Access Eth - Bridge",
    "secondary_wan": "WAN-2",
    "secondary_cct": "Lanka Com",
    "secondary_bw": "2 Mbps",
    "secondary_service": "Lanka Com"
  },
  {
    "attached": "Device",
    "branch_code": "MB006",
    "branch_name": "Gonagaldeniya",
    "province": "SAB",
    "branch_lan_ip": "172.31.213.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D69082",
    "primary_bw": "2 Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "Lanka Com",
    "secondary_bw": "2 Mbps",
    "secondary_service": "Lanka Com"
  },
  {
    "attached": "Device",
    "branch_code": "MB007",
    "branch_name": "Gonagolla",
    "province": "EP",
    "branch_lan_ip": "172.31.139.254",
    "primary_wan": "WAN-1",
    "primary_cct": "E1106222/D47814",
    "primary_bw": "2 Mbps",
    "primary_service": "One Access Eth - Bridge",
    "secondary_wan": "WAN-2",
    "secondary_cct": "LCN",
    "secondary_bw": "2 Mbps",
    "secondary_service": "LCN"
  },
  {
    "attached": "Device",
    "branch_code": "MB008",
    "branch_name": "Gonapola",
    "province": "WPS",
    "branch_lan_ip": "172.31.145.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D67519",
    "primary_bw": "2 Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "DBN IP VPN",
    "secondary_bw": "2 Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB009",
    "branch_name": "Gothatuwa New Town",
    "province": "WPN",
    "branch_lan_ip": "172.17.176.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D58991",
    "primary_bw": "2 Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "DBN IP VPN",
    "secondary_bw": "2 Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB010",
    "branch_name": "Grandpass",
    "province": "WPN",
    "branch_lan_ip": "172.17.1.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D63546",
    "primary_bw": "2 Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "Lanka Com",
    "secondary_bw": "2 Mbps",
    "secondary_service": "Lanka Com"
  },
 {
    "attached": "Device",
    "branch_code": "MB001",
    "branch_name": "Main Branch",
    "province": "Western",
    "branch_lan_ip": "192.168.1.1",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-120",
    "primary_bw": "100Mbps",
    "primary_service": "Fiber",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "50Mbps",
    "secondary_service": "DSL"
  },
  {
    "attached": "Device",
    "branch_code": "G001",
    "branch_name": "Gurugoda (Bodyline)",
    "province": "Western",
    "branch_lan_ip": "172.31.166.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-120",
    "primary_bw": "2Mbps",
    "primary_service": "SLT",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "Backup Line"
  },
  {
    "attached": "Device",
    "branch_code": "H001",
    "branch_name": "Habarana",
    "province": "NCP",
    "branch_lan_ip": "172.17.227.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-150",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "H002",
    "branch_name": "Hakmana",
    "province": "SP",
    "branch_lan_ip": "172.16.232.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-140",
    "primary_bw": "2Mbps",
    "primary_service": "DSL",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "H003",
    "branch_name": "Haldummulla",
    "province": "UVA",
    "branch_lan_ip": "172.17.111.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-160",
    "primary_bw": "2Mbps",
    "primary_service": "Fiber",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "DSL"
  },
  {
    "attached": "Device",
    "branch_code": "H004",
    "branch_name": "Hali-Ela",
    "province": "UVA",
    "branch_lan_ip": "172.31.171.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-170",
    "primary_bw": "2Mbps",
    "primary_service": "Fiber",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "LCN"
  },
  {
    "attached": "Device",
    "branch_code": "H005",
    "branch_name": "Hambantota",
    "province": "SP",
    "branch_lan_ip": "172.16.32.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-180",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "H006",
    "branch_name": "Hanwella",
    "province": "WPS",
    "branch_lan_ip": "172.16.202.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-190",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "H007",
    "branch_name": "Haputale",
    "province": "UVA",
    "branch_lan_ip": "172.16.240.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-200",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "Lanka Com"
  },
  {
    "attached": "Device",
    "branch_code": "H008",
    "branch_name": "Hasalaka",
    "province": "UVA",
    "branch_lan_ip": "172.17.17.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-210",
    "primary_bw": "2Mbps",
    "primary_service": "Fiber",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "LCN"
  },
 {
    "attached": "Device",
    "branch_code": "MB001",
    "branch_name": "Hatton",
    "province": "Central",
    "branch_lan_ip": "172.16.88.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-120",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "2Mbps",
    "secondary_service": "Lanka Com"
  },
  {
    "attached": "Device",
    "branch_code": "MB002",
    "branch_name": "Hemmathagama",
    "province": "Sabaragamuwa",
    "branch_lan_ip": "172.17.86.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-130",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-210",
    "secondary_bw": "2Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB003",
    "branch_name": "Hettipola",
    "province": "North Western",
    "branch_lan_ip": "172.16.241.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-140",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-220",
    "secondary_bw": "2Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB004",
    "branch_name": "Hikkakaduwa",
    "province": "Southern",
    "branch_lan_ip": "172.16.33.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-150",
    "primary_bw": "2Mbps",
    "primary_service": "SLT Routed",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-230",
    "secondary_bw": "2Mbps",
    "secondary_service": "Lanka Com"
  },
  {
    "attached": "Device",
    "branch_code": "MB005",
    "branch_name": "Hingurakgoda",
    "province": "North Central",
    "branch_lan_ip": "172.16.89.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-160",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-240",
    "secondary_bw": "2Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB006",
    "branch_name": "Hingurana",
    "province": "Eastern",
    "branch_lan_ip": "172.17.46.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-170",
    "primary_bw": "2Mbps",
    "primary_service": "SLT Routed",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-250",
    "secondary_bw": "2Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB007",
    "branch_name": "Hiripitiya",
    "province": "North Western",
    "branch_lan_ip": "172.16.245.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-180",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-260",
    "secondary_bw": "2Mbps",
    "secondary_service": "Lanka Com"
  },
  {
    "attached": "Device",
    "branch_code": "MB008",
    "branch_name": "Homagama",
    "province": "Western",
    "branch_lan_ip": "172.16.34.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-190",
    "primary_bw": "2Mbps",
    "primary_service": "SLT Routed",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-270",
    "secondary_bw": "2Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB009",
    "branch_name": "Horana",
    "province": "Western",
    "branch_lan_ip": "172.16.35.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-200",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-280",
    "secondary_bw": "2Mbps",
    "secondary_service": "DBN IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "MB010",
    "branch_name": "Horawpothana",
    "province": "North Central",
    "branch_lan_ip": "172.17.83.254",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-210",
    "primary_bw": "2Mbps",
    "primary_service": "SLT Routed",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-290",
    "secondary_bw": "2Mbps",
    "secondary_service": "Lanka Com"
  },
 {
    'attached': 'Device',
    'branch_code': 'MB001',
    'branch_name': 'Main Branch',
    'province': 'Western',
    'branch_lan_ip': '172.16.3.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-120',
    'primary_bw': '100Mbps',
    'primary_service': 'Fiber',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-200',
    'secondary_bw': '50Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'HYD001',
    'branch_name': 'Hyde Park',
    'province': 'Western',
    'branch_lan_ip': '172.16.36.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-130',
    'primary_bw': '100Mbps',
    'primary_service': 'Fiber',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-210',
    'secondary_bw': '50Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'IBG001',
    'branch_name': 'Ibbagamuwa',
    'province': 'North Western',
    'branch_lan_ip': '172.17.144.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-140',
    'primary_bw': '100Mbps',
    'primary_service': 'Fiber',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-220',
    'secondary_bw': '50Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'PAN001',
    'branch_name': 'Pandatharippu (Ilavallai)',
    'province': 'Northern',
    'branch_lan_ip': '172.19.32.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-150',
    'primary_bw': '100Mbps',
    'primary_service': 'Fiber',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-230',
    'secondary_bw': '50Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'IMA001',
    'branch_name': 'Imaduwa',
    'province': 'Southern',
    'branch_lan_ip': '172.17.68.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-160',
    'primary_bw': '100Mbps',
    'primary_service': 'Fiber',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-240',
    'secondary_bw': '50Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'IST001',
    'branch_name': 'Independent Square (Torrington)',
    'province': 'Western',
    'branch_lan_ip': '172.16.132.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-170',
    'primary_bw': '100Mbps',
    'primary_service': 'Fiber',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-250',
    'secondary_bw': '50Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'ING001',
    'branch_name': 'Ingiriya',
    'province': 'Western',
    'branch_lan_ip': '172.16.198.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-180',
    'primary_bw': '100Mbps',
    'primary_service': 'Fiber',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-260',
    'secondary_bw': '50Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'IPA001',
    'branch_name': 'Ipalogama',
    'province': 'North Central',
    'branch_lan_ip': '172.17.112.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-190',
    'primary_bw': '100Mbps',
    'primary_service': 'Fiber',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-270',
    'secondary_bw': '50Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'IRK001',
    'branch_name': 'Irakkamam',
    'province': 'Eastern',
    'branch_lan_ip': '172.31.240.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-200',
    'primary_bw': '100Mbps',
    'primary_service': 'Fiber',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-280',
    'secondary_bw': '50Mbps',
    'secondary_service': 'DSL'
  },
  {
    'attached': 'Device',
    'branch_code': 'JAE001',
    'branch_name': 'Ja-Ela (Routed to SLT with Backup line)',
    'province': 'Western',
    'branch_lan_ip': '172.16.38.254',
    'primary_wan': 'WAN-1',
    'primary_cct': 'CCT-210',
    'primary_bw': '100Mbps',
    'primary_service': 'Fiber',
    'secondary_wan': 'WAN-2',
    'secondary_cct': 'CCT-290',
    'secondary_bw': '50Mbps',
    'secondary_service': 'DSL'
  },
 {
    "attached": "Device",
    "branch_code": "MB001",
    "branch_name": "Main Branch",
    "province": "Western",
    "branch_lan_ip": "192.168.1.1",
    "primary_wan": "WAN-1",
    "primary_cct": "CCT-120",
    "primary_bw": "100Mbps",
    "primary_service": "Fiber",
    "secondary_wan": "WAN-2",
    "secondary_cct": "CCT-200",
    "secondary_bw": "50Mbps",
    "secondary_service": "DSL"
  },
  {
    "attached": "Device",
    "branch_code": "JB001",
    "branch_name": "Jaffna",
    "province": "NP",
    "branch_lan_ip": "172.16.192.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D61463",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "DBN IP VPN",
    "secondary_bw": "2Mbps",
    "secondary_service": "IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "JB002",
    "branch_name": "Jaffna 2nd",
    "province": "NP",
    "branch_lan_ip": "172.31.11.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D61078",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "DBN IP VPN",
    "secondary_bw": "2Mbps",
    "secondary_service": "IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "JB003",
    "branch_name": "Jaffna Bus Stand",
    "province": "NP",
    "branch_lan_ip": "172.31.44.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D69628",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN-One Access",
    "secondary_wan": "WAN-2",
    "secondary_cct": "DBN IP VPN",
    "secondary_bw": "2Mbps",
    "secondary_service": "IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "JB004",
    "branch_name": "Jaffna Main Street",
    "province": "NP",
    "branch_lan_ip": "172.31.70.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D65009",
    "primary_bw": "2Mbps",
    "primary_service": "",
    "secondary_wan": "WAN-2",
    "secondary_cct": "LCN",
    "secondary_bw": "2Mbps",
    "secondary_service": "LCN"
  },
  {
    "attached": "Device",
    "branch_code": "JB005",
    "branch_name": "Jaffna University",
    "province": "NP",
    "branch_lan_ip": "172.31.236.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D63110",
    "primary_bw": "2Mbps",
    "primary_service": "OA Eth Bridge",
    "secondary_wan": "WAN-2",
    "secondary_cct": "DBN IP VPN",
    "secondary_bw": "2Mbps",
    "secondary_service": "IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "JP001",
    "branch_name": "Jayanthipura",
    "province": "NCP",
    "branch_lan_ip": "172.17.98.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D53316",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN-RF",
    "secondary_wan": "WAN-2",
    "secondary_cct": "DBN IP VPN",
    "secondary_bw": "2Mbps",
    "secondary_service": "IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "JH001",
    "branch_name": "Jayawardenapura Hospital",
    "province": "WPS",
    "branch_lan_ip": "172.16.144.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D61757",
    "primary_bw": "2Mbps",
    "primary_service": "",
    "secondary_wan": "WAN-2",
    "secondary_cct": "DBN IP VPN",
    "secondary_bw": "2Mbps",
    "secondary_service": "IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "KD001",
    "branch_name": "Kadawatha",
    "province": "WPN",
    "branch_lan_ip": "172.16.90.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D51634",
    "primary_bw": "2Mbps",
    "primary_service": "IP VPN",
    "secondary_wan": "WAN-2",
    "secondary_cct": "DBN IP VPN",
    "secondary_bw": "2Mbps",
    "secondary_service": "IP VPN"
  },
  {
    "attached": "Device",
    "branch_code": "KD002",
    "branch_name": "Kadawatha 2nd City (Routed)",
    "province": "WPN",
    "branch_lan_ip": "172.31.152.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D66412",
    "primary_bw": "2Mbps",
    "primary_service": "",
    "secondary_wan": "WAN-2",
    "secondary_cct": "LCN",
    "secondary_bw": "2Mbps",
    "secondary_service": "LCN"
  },
  {
    "attached": "Device",
    "branch_code": "KD003",
    "branch_name": "Kaduruwela",
    "province": "NCP",
    "branch_lan_ip": "172.16.39.254",
    "primary_wan": "WAN-1",
    "primary_cct": "D66415",
    "primary_bw": "2Mbps",
    "primary_service": "",
    "secondary_wan": "WAN-2",
    "secondary_cct": "DBN IP VPN",
    "secondary_bw": "2Mbps",
    "secondary_service": "IP VPN"
  }
];

